###### DEV PIPELINE ######
image: docker:27.3.1
services:
  - name: docker:27.3.1-dind
    alias: docker 
    command: [ "--tls=false", "--mtu=1240" ]
    privileged: true
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
#  - deploy

build_docker_image_dev:
  stage: build
  only:
    - main
    #- version/demo-stable
  script:
    - apk add --no-cache git
    - git clone https://$GIT_USERNAME:$GIT_PASSWORD@git-az.nosi.cv/simple-servico/backends/simple-backend.git .
    - docker login $REGISTRY_URL -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD" 
    - docker build -t $REGISTRY_URL/$REGISTRY_PROJECT/simple-utente:$CI_PIPELINE_ID .
    - docker tag $REGISTRY_URL/$REGISTRY_PROJECT/simple-utente:$CI_PIPELINE_ID $REGISTRY_URL/$REGISTRY_PROJECT/simple-utente:latest
    - docker push $REGISTRY_URL/$REGISTRY_PROJECT/simple-utente:$CI_PIPELINE_ID
    - docker push $REGISTRY_URL/$REGISTRY_PROJECT/simple-utente:latest
